[package]
name = "bender_bouncer"
version = "0.1.0"
authors = ["David Huss <dh@widerstandzwecklos.at>"]
workspace = ".."

[dependencies]
docopt = "1"
serde = "1"
serde_derive = "1"
colored = "1.6"
flate2 = "1.0"